### ISSUE TITLE
Deploy succeeded but sending images causes the following (DeployDeepLearning)

### ISSUE THREAD

**Issue by al-yakubovich** [ashish735/FunProjects#5]
Hi! The project looks very cool!

I tried to run it with `docker-compose up --build`. It started fine. When I've uploaded an image via web interface I got "Internal Server Error". Here are logs: 

```
client: 172.19.0.1, server: , request: "POST /app HTTP/1.1", host: "localhost:1337", referrer: "https://localhost:1337/app"
web_1                 | static/WIN_20210111_16_51_01_Pro.jpg
web_1                 | [2021-01-28 20:59:00,511] ERROR in app: Exception on /app [POST]
web_1                 | Traceback (most recent call last):
web_1                 |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
web_1                 |     (self._dns_host, self.port), self.timeout, **extra_kw
web_1                 |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
web_1                 |     raise err
web_1                 |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
web_1                 |     sock.connect(sa)
web_1                 | ConnectionRefusedError: [Errno 111] Connection refused
web_1                 |
web_1                 | During handling of the above exception, another exception occurred:
web_1                 |
web_1                 | Traceback (most recent call last):
web_1                 |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
web_1                 |     chunked=chunked,
web_1                 |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
web_1                 |     conn.request(method, url, **httplib_request_kw)
web_1                 |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
web_1                 |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
web_1                 |   File "/usr/local/lib/python3.7/http/client.py", line 1277, in request
web_1                 |     self._send_request(method, url, body, headers, encode_chunked)
web_1                 |   File "/usr/local/lib/python3.7/http/client.py", line 1323, in _send_request
web_1                 |     self.endheaders(body, encode_chunked=encode_chunked)
web_1                 |   File "/usr/local/lib/python3.7/http/client.py", line 1272, in endheaders
web_1                 |     self._send_output(message_body, encode_chunked=encode_chunked)
web_1                 |   File "/usr/local/lib/python3.7/http/client.py", line 1032, in _send_output
web_1                 |     self.send(msg)
web_1                 |   File "/usr/local/lib/python3.7/http/client.py", line 972, in send
web_1                 |     self.connect()
web_1                 |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 200, in connect
web_1                 |     conn = self._new_conn()
web_1                 |   File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
web_1                 |     self, "Failed to establish a new connection: %s" % e
web_1                 | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7d4918b190>: Failed to establish a new connection: [Errno 111] Connection refused
web_1                 |
web_1                 | During handling of the above exception, another exception occurred:
web_1                 |
web_1                 | Traceback (most recent call last):
web_1                 |   File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
web_1                 |     timeout=timeout
web_1                 |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
web_1                 |     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
web_1                 |   File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
web_1                 |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
web_1                 | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tensorflow-serving', port=8501): Max retries exceeded with url: /v1/models/my_model:predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d4918b190>: Failed to establish a new connection: [Errno 111] Connection refused'))
web_1                 |
web_1                 | During handling of the above exception, another exception occurred:
web_1                 |
web_1                 | Traceback (most recent call last):
web_1                 |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
web_1                 |     response = self.full_dispatch_request()
web_1                 |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
web_1                 |     rv = self.handle_user_exception(e)
web_1                 |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
web_1                 |     reraise(exc_type, exc_value, tb)
web_1                 |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
web_1                 |     raise value
web_1                 |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
web_1                 |     rv = self.dispatch_request()
web_1                 |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
web_1                 |     return self.view_functions[rule.endpoint](**req.view_args)
web_1                 |   File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
web_1                 |     return func(*args, **kwargs)
web_1                 |   File "/app/app.py", line 65, in predict
web_1                 |     class_name = model.get_prediction(image_path)
web_1                 |   File "/app/model.py", line 86, in get_prediction
web_1                 |     response = requests.post(MODEL_URI, data=data.encode('utf-8'))
web_1                 |   File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 119, in post
web_1                 |     return request('post', url, data=data, json=json, **kwargs)
web_1                 |   File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
web_1                 |     return session.request(method=method, url=url, **kwargs)
web_1                 |   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
web_1                 |     resp = self.send(prep, **send_kwargs)
web_1                 |   File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
web_1                 |     r = adapter.send(request, **kwargs)
web_1                 |   File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
web_1                 |     raise ConnectionError(e, request=request)
web_1                 | requests.exceptions.ConnectionError: HTTPConnectionPool(host='tensorflow-serving', port=8501): Max retries exceeded with url: /v1/models/my_model:predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d4918b190>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

It looks like here is some problem with tensorflow serving container. Any ideas would be appreciated.

Thanks for your awesome project!

**Comment by ashish735** [comment]
Hello! Thanks for the appreciation. This error is coming because maybe you have not created the "cert.pem" and "key.pem" files which are needed to run web application via the "HTTPS" port. 
You can either create "cert.pem" and "key.pem" by following my [blog](https://medium.com/thecyphy/deploy-deep-learning-model-using-docker-tensorflow-serving-nginx-and-flask-part-3-3a2a77620e1f)
OR you can run web application via the "HTTP" port by following below steps-
1. Rename the file "nginx_NotSecure.conf" in the folder "services/nginx" to "nginx.conf"
2. Edit the "ports" section in "docker-compose.yml" file, change "1337:443" to "1337:80"

**Comment by al-yakubovich** [comment]
@ashish735 
Thanks for answer.
I created "cert.pem" and "key.pem" but I am still getting the same error. Also I tried to run web application via the "HTTP" port but it is doesn't work as well.

It looks like there is problem with tensorflow-serving's container when it starts. Here its logs:

```
tensorflow-serving_1  | 2021-01-29 18:19:06.253100: I tensorflow_serving/model_servers/server_core.cc:464] Adding/updating models.
tensorflow-serving_1  | 2021-01-29 18:19:06.253166: I tensorflow_serving/model_servers/server_core.cc:587]  (Re-)adding model: my_model
tensorflow-serving_1  | 2021-01-29 18:19:06.253179: I tensorflow_serving/model_servers/server_core.cc:587]  (Re-)adding model: detect_model
web_1                 | [2021-01-29 18:19:06 +0000] [1] [INFO] Starting gunicorn 20.0.4
web_1                 | [2021-01-29 18:19:06 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
web_1                 | [2021-01-29 18:19:06 +0000] [1] [INFO] Using worker: sync
tensorflow-serving_1  | 2021-01-29 18:19:06.353721: I tensorflow_serving/core/basic_manager.cc:740] Successfully reserved resources to load servable {name: my_model version: 1}
tensorflow-serving_1  | 2021-01-29 18:19:06.353783: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: my_model version: 1}
tensorflow-serving_1  | 2021-01-29 18:19:06.353804: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: my_model version: 1}
tensorflow-serving_1  | 2021-01-29 18:19:06.353865: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:32] Reading SavedModel from: /models/my_model/1
web_1                 | [2021-01-29 18:19:06 +0000] [9] [INFO] Booting worker with pid: 9
tensorflow-serving_1  | 2021-01-29 18:19:06.361452: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:55] Reading meta graph with tags { serve }
tensorflow-serving_1  | 2021-01-29 18:19:06.361556: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:93] Reading SavedModel debug info (if present) from: /models/my_model/1
tensorflow-serving_1  | 2021-01-29 18:19:06.361672: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
tensorflow-serving_1  | To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
tensorflow-serving_1  | 2021-01-29 18:19:06.410418: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
tensorflow-serving_1  | 2021-01-29 18:19:06.413252: I external/org_tensorflow/tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2304005000 Hz
tensorflow-serving_1  | 2021-01-29 18:19:06.453692: I tensorflow_serving/core/basic_manager.cc:740] Successfully reserved resources to load servable {name: detect_model version: 1}
tensorflow-serving_1  | 2021-01-29 18:19:06.453756: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: detect_model version: 1}
tensorflow-serving_1  | 2021-01-29 18:19:06.453775: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: detect_model version: 1}
tensorflow-serving_1  | 2021-01-29 18:19:06.453813: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:32] Reading SavedModel from: /models/detect_model/1
tensorflow-serving_1  | 2021-01-29 18:19:06.557360: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:190] Running initialization op on SavedModel bundle at path: /models/my_model/1
tensorflow-serving_1  | 2021-01-29 18:19:06.573367: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: success: OK. Took 219502 microseconds.
tensorflow-serving_1  | 2021-01-29 18:19:06.575737: I tensorflow_serving/servables/tensorflow/saved_model_warmup_util.cc:59] No warmup data file found at /models/my_model/1/assets.extra/tf_serving_warmup_requests
tensorflow-serving_1  | 2021-01-29 18:19:06.577632: I tensorflow_serving/core/loader_harness.cc:87] Successfully loaded servable version {name: my_model version: 1}
tensorflow-serving_1  | 2021-01-29 18:19:06.599139: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:55] Reading meta graph with tags { serve }
tensorflow-serving_1  | 2021-01-29 18:19:06.599194: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:93] Reading SavedModel debug info (if present) from: /models/detect_model/1
tensorflow-serving_1  | 2021-01-29 18:19:07.256268: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
tensorflow-serving_1  | 2021-01-29 18:19:08.426827: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at save_restore_v2_ops.cc:205 : Data loss: not an sstable (bad magic number)
tensorflow-serving_1  | 2021-01-29 18:19:08.429650: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: fail: Data loss: not an sstable (bad magic number)
tensorflow-serving_1  |          [[{{node RestoreV2}}]]. Took 1975840 microseconds.
tensorflow-serving_1  | 2021-01-29 18:19:08.429725: E tensorflow_serving/util/retrier.cc:37] Loading servable: {name: detect_model version: 1} failed: Data loss: not an sstable (bad magic number)
tensorflow-serving_1  |          [[{{node RestoreV2}}]]
tensorflow-serving_1  | 2021-01-29 18:20:08.429928: I tensorflow_serving/util/retrier.cc:33] Retrying of Loading servable: {name: detect_model version: 1} retry: 1
tensorflow-serving_1  | 2021-01-29 18:20:08.679048: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:32] Reading SavedModel from: /models/detect_model/1
tensorflow-serving_1  | 2021-01-29 18:20:08.760868: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:55] Reading meta graph with tags { serve }
tensorflow-serving_1  | 2021-01-29 18:20:08.760926: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:93] Reading SavedModel debug info (if present) from: /models/detect_model/1
tensorflow-serving_1  | 2021-01-29 18:20:08.995930: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:206] Restoring SavedModel bundle.
tensorflow-serving_1  | 2021-01-29 18:20:09.818081: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at save_restore_v2_ops.cc:205 : Data loss: not an sstable (bad magic number)
tensorflow-serving_1  | 2021-01-29 18:20:09.820704: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:277] SavedModel load for tags { serve }; Status: fail: Data loss: not an sstable (bad magic number)
tensorflow-serving_1  |          [[{{node RestoreV2}}]]. Took 1141662 microseconds.
tensorflow-serving_1  | 2021-01-29 18:20:09.820790: E tensorflow_serving/util/retrier.cc:37] Loading servable: {name: detect_model version: 1} failed: Data loss: not an sstable (bad magic number)
tensorflow-serving_1  |          [[{{node RestoreV2}}]]

```

So it seems that pretrained model doesn't run correctly.

**Comment by ashish735** [comment]
@al-yakubovich I build and run the docker container at my end today, it is working fine for both HTTP and HTTPS port, please check the setting of below three files while running the container -
1. Dockerfile.nginx : the configuration of the "nginx.conf" file. Two separate "nginx.conf" files are there for HTTP and HTTPS settings
2. Docker-compose.yml : nginx section. Which port is open ? "1337:443 for HTTPS" and "1337:80 for HTTP"
3. model.py file in "services\web\flask" : Check line 14 MODEL_URI, whether it is "http:://tensorflow-..." or "https://tensorflow-..."

**Comment by ashish735** [comment]
@al-yakubovich One more thing, if you build a docker image and then make some changes in the files like .py files or nginx.conf files, then you have to delete the old docker image build the docker image again to make those changes reflect in your created images.

**Comment by al-yakubovich** [comment]
@ashish735 

Thanks for your answers. I played around with container for tensoflow-serving and have found that if you comment out code for `detect_model` in `model.config` everything starts working. Not sure what's wrong with `detect_model`  but for this model `variables.index` and `variables.data-00000-of-00001` are ASCII text files.

At the same time files for `my_model`: `variables.index`, `variables.data-00000-of-00002` and `variables.data-00001-of-00002` are not ASCII.

Probably there was some issue when `detect_model` was saved.

Anyway `detect_model` works great. Thanks again for awesome project!
